### PR TITLE
Space Travelers Hub React-Redux Group Project

### PR DESCRIPTION
**Pull request by sebalp100**
# Space Travelers Hub React-Redux Group Project

In this project, we are setting up a website that allows users to reserve and book their favorite rockets, missions, and dragon spaceships, using real live data from the SpaceX API.

We implemented the following:

- Created a Rockets Page allowing the user to reserve different rockets with the data we fetch from the API.
- Created a Missions Page allowing the user to join different missions with the data we fetch from the API.
- Created a Dragons Page allowing the user to reserve different dragons with the data we fetch from the API.
- Created a My Profile page that displays all the missions, rockets, and dragons the user has reserved.
- Added cancel functions to remove reserved rockets and dragons, and to leave missions.
- Added tests using React Testing Library
- Used Kanban board to distribute the workload
- Page style was followed in accordance with the template provided.

The workload distribution for this project was as follows:

- @sebalp100  was in charge of missions
- @amentetteh was in charge of dragons
- @SimonGideon was in charge of rockets

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @sebalp100, @amentetteh and @SimonGideon, kindly add the future features section to your readme

**Comment by sebalp100** [comment]
Hi @prolajumokeoni, Future Features section implemented 👍

**Review by prolajumokeoni — APPROVED** [review]
Hi @sebalp100, @amentetteh and @SimonGideon  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Readme ✍🏿 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sebalp100** [comment]
Thank you for your review @prolajumokeoni 👍

**Pull request merged**
